# Generated by Django 4.2.11 on 2024-04-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
